FROM ruby:2.5
RUN apt-get update && apt-get install -y \
 build-essential \
 libpq-dev \
 nodejs \
 postgresql-client \
 yarn
WORKDIR /ds_rails
COPY Gemfile Gemfile.lock /ds_rails/
RUN bundle install
COPY ..
CMD ["rails","s"]